plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page/:num"
baseurl: ""

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js, toc.js]

title: "ApexDevForce.com"
email: zhouhu at hotmail dot com
description: ""
github:
  username: zhouhu
swiftype:
  searchId: JPbWRdep_zjQxkH55XKs
gitment:
    repo: apexdevforce
    client_id: 1899897df7eb33ce034d
    client_secret: 35daf904cc7676aa6e63bcf6ad3424cb5226a20d

url: "https://apexdevforce.com"
imgrepo: "https://apexdevforce.com/static/img"

#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
